package com.javagradle.demo;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'LENOVO' at '11/28/16 3:16 PM' with Gradle 2.14.1
 *
 * @author LENOVO, @date 11/28/16 3:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
