package com.javagradle.test;
import org.junit.Test;

import com.javagradle.demo.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'LENOVO' at '11/28/16 3:16 PM' with Gradle 2.14.1
 *
 * @author LENOVO, @date 11/28/16 3:16 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
